=== Malherebastien/Projet_Tut_S3/src/element.dtd
<!ELEMENT formulaire (JTextField*, JLabel*, JComboBox*, JCheckBox*, JRadioButton*)>
	<!ELEMENT JTextField EMPTY>
		<!ATTLIST JTextField    label CDATA #REQUIRED
										   id ID    #REQUIRED
								   	    x CDATA #REQUIRED 
								          y CDATA #REQUIRED
						          largeur CDATA #REQUIRED
							          type (int | String | Double | boolean | float) "String" >
	<!ELEMENT JLabel EMPTY>
		<!ATTLIST JLabel        label CDATA #REQUIRED
										   id ID    #REQUIRED
								   	    x CDATA #REQUIRED 
								          y CDATA #REQUIRED
						          largeur CDATA #REQUIRED>
	<!ELEMENT JComboBox (comboBox+)>
		<!ATTLIST JComboBox     label CDATA #REQUIRED
										   id ID    #REQUIRED
								   	    x CDATA #REQUIRED 
								          y CDATA #REQUIRED
						          largeur CDATA #REQUIRED
							          type (int | String | Double | boolean | float) "String" >
	<!ELEMENT comboBox (#PCDATA)>
	<!ELEMENT JCheckBox (checkBox+)>
		<!ATTLIST JCheckBox     label CDATA #REQUIRED
										   id ID    #REQUIRED
								   	    x CDATA #REQUIRED 
								          y CDATA #REQUIRED
						          largeur CDATA #REQUIRED
							          type (int | String | Double | boolean | float) "String" >
	<!ELEMENT checkBox (#PCDATA)>
	<!ELEMENT JRadioButton (radioButton+)>
		<!ATTLIST JRadioButton  label CDATA #REQUIRED
										   id ID    #REQUIRED
								   	    x CDATA #REQUIRED 
								          y CDATA #REQUIRED
						          largeur CDATA #REQUIRED
							          type (int | String | Double | boolean | float) "String" >
	<!ELEMENT radioButton (#PCDATA)>
	<!ELEMENT Tableau EMPTY> 
		<!ATTLIST Tableau label CDATA #IMPLIED
								  col CDATA #REQUIRED
								  lig CDATA #IMPLIED 
								 type (int | String | Double | boolean | float) "String">
	<!ELEMENT JSpinner (#PCDATA)>
	
	<!ELEMENT Calendrier EMPTY>
		<!ATTLIST Calendrier			 x CDATA #REQUIRED 
								          y CDATA #REQUIRED
						          		 largeur CDATA #REQUIRED>

=== Malherebastien/Projet_Tut_S3/Test2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE formulaire SYSTEM "element.dtd">
<formulaire>
	<JTextField id="1" x="150" y="100" largeur="150" value="Nom" type="String"/>
	<JTextField id="2" x="300" y="100" largeur="200" value="Prenom" type="String"/>
	<JLabel id="3" x="150" y="50"  largeur="200" value="Partie 1" type="void"/>
	<JComboBox id="4" x="150" y="50" largeur="200" value="Choix couleur"  type="String">
		<comboBox>rouge</comboBox>
		<comboBox>bleu</comboBox>
		<comboBox>vert</comboBox>
	</JComboBox>
	<JCheckBox id="5" x="150" y="50" largeur="200" value="Nom de la paire" type="String">
		<checkBox>rouge</checkBox>
		<checkBox>bleu</checkBox>
		<checkBox>vert</checkBox>
	</JCheckBox>
	<JLabel id="6" x="150" y="50"  largeur="200" value="Partie 1" type="void"/>
	<JRadioButton id="7" x="150" y="50" largeur="200" value="Choix unique" type="int">
		<radioButton>1</radioButton>
		<radioButton>2</radioButton>
		<radioButton>3</radioButton>
		<radioButton>4</radioButton>
	</JRadioButton>
</formulaire>

=== Malherebastien/Projet_Tut_S3/src/Test2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE formulaire SYSTEM "element.dtd">
<formulaire>
	<JTextField label="Nom"  id="1" x="100" y="50" largeur="150" type="int"/>
	<JTextField label="Prenom" id="2" x="100" y="100" largeur="150"  type="String"/>
	<JComboBox label="Choix couleur"   id="3" x="100" y="200" largeur="150" type="String">
		<comboBox>A</comboBox>
		<comboBox>c</comboBox>
		<comboBox>vert</comboBox>
	</JComboBox>
	<JSpinner label="Spinner"  id="5" x="100" y="500"  largeur="150" type="int"/>
	<JCheckBox label="Nom de la paire"  id="4" x="100" y="250" largeur="70" type="String">
		<checkBox id="4a">2</checkBox>
		<checkBox id="4b">4</checkBox>
		<checkBox id="4c">6</checkBox>
	</JCheckBox>
	<JRadioButton label="Choix unique"  id="6" x="100" y="350" largeur="150" type="int">
		<radioButton id="6a">1</radioButton>
	</JRadioButton>
	<Tableau label="tableau" id="7" col="5" lig="5" type="String" dimension="2" longueur="300" largeur="300" x="500" y ="400"/>
	<!-- <Tableau label="tableau 1 dim"  col="8" type="String"/> -->
	<!-- <Calendrier x="150" y="50" largeur="200"/> -->
</formulaire>
